interval-in-hours: 1
questions:
  - "What do you think of the latest update?"
  - "Would you recommend this server to a friend?"
  - "How do you feel about how the server is managed?"
  - "Do you like our staff members?"
  - "What aspect of the server do you like the most?"